# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=128)),
                ('role', models.IntegerField()),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
